datasources:
  postgres:
    url: jdbc:postgresql://kestra_db:5432/kestra
    # Database location and connection protocol (jdbc)
    driverClassName: org.postgresql.Driver
    # PostgreSQL JDBC driver class name
    username: cll
    password: cll2025
kestra:
  server:
    basic-auth:
      username: "chen.linliang@gmail.com"
      password: d6b5b3887ab4ed57cec6ad9fc416d3a0e5f6855ee6838ba1a0690df3b8b8d9f9
  repository:
    type: postgres
  storage:
    type: local
    local:
      basePath: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/