volumes:
  pgdata:
    driver: local
  kestra_pgdata:
    driver: local
  kestra_data:
    driver: local
  pgadmin_data:
    driver: local

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ny_taxi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  kestra_db:
    image: postgres:18
    volumes:
      - kestra_pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kestra123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 15s
      timeout: 10s
      retries: 5

  kestra:
    image: kestra/kestra:v1.1
    pull_policy: always
    user: "root"
    command: server standalone 
    # --config /app/confs/configuration.yaml
    # Explicitly load YAML settings to override the defaults (url, db, etc)
    volumes:
    #  - ./kestra/configuration.yaml:/app/confs/configuration.yaml <= didn't work out
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    env_file:
      - .env
      - .env_encoded
    environment:
      SECRET_GCP_CREDS: ${SECRET_GCP_CREDS}
      SECRET_GEMINI_API_KEY: ${SECRET_GEMINI_API_KEY}
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_db:5432/kestra
            # Database location and connection protocol (jdbc)
            driverClassName: org.postgresql.Driver
            # PostgreSQL JDBC driver class name
            username: admin #kestra_db user
            password: kestra123 #kestra_db password
        kestra:
          ai:
            type: gemini
            gemini:
              model-name: gemini-2.5-flash
              api-key: ${SECRET_GEMINI_API_KEY}
          server:
            basic-auth:
              username: "admin@kestra.io" 
              password: "Admin1234"
              # default: admin@kestra.io:Admin1234
              # custom doesn't work : admin@admin.com:admin123
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          # url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on: 
      kestra_db :
        condition: service_healthy
        # healthy is better than started

  pgadmin:
    image: dpage/pgadmin4:latest
  # Tooling only â€“ not part of the data platform
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"